FROM registry.access.redhat.com/rhel:latest

MAINTAINER gidikern <gidikern@gmail.com>

RUN yum install -y java-1.8.0-openjdk java-1.8.0-openjdk-devel && \
yum clean all

# Define default command.
CMD ["bash"]
